### ISSUE TITLE
Bug with power

### ISSUE THREAD

**Issue by gajotnt** [jello1974/duosidaEV-home-assistant#1]
Hello there, my trip got delayed a couple of days and i got time to test this

everything works great so far but the power isnt right.

It should display 2.6kw and its displaying 2600kw
I have another sensor (Zoe) that shows the correct wattage
![Power diference](https://user-images.githubusercontent.com/25504364/222936885-d61f278e-707a-410e-803d-e9b8966a4c5d.png)
![Screenshot 2023-03-05 003558](https://user-images.githubusercontent.com/25504364/222936889-7c22ba7c-6003-4923-af7a-0dd527068cec.png)
If i change the unit from Kw to W:
![Screenshot 2023-03-05 0035581](https://user-images.githubusercontent.com/25504364/222936953-ad94819d-eb5a-480f-a042-fe5431d848cf.png)

Maybe its DuoSida thats giving the wrong number, or maybe in the integration something is being misscalculated?

Edit:
In the D's charge app the power show correctly 

![Screenshot_2023-03-05-02-54-08-35_a1b04ade13b213170352e8cdc86048f6](https://user-images.githubusercontent.com/25504364/222940811-3c8b58f3-4dd9-4f71-b5b2-e2f05a22ddfe.jpg)

**Comment by gajotnt** [comment]
https://github.com/jello1974/duosidaEV-home-assistant/blob/main/custom_components/duosida/duosida.py

Maybe this should go from this:
```
    DuosidaSensorEntityDescription(
        key=DeviceDetail.POWER,
        name=f"{NAME} Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        get_native_value=DuosidaDevice.get_device_power,
    ),
```

To this?
```
    DuosidaSensorEntityDescription(
        key=DeviceDetail.POWER,
        name=f"{NAME} Power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.WATT,
        get_native_value=DuosidaDevice.get_device_power,
    ),
```
Dont know how to code, just had a look on your code and... well i tried... xD

**Comment by jello1974** [comment]
Hello,

 

Yes you’re wright. I didn’t use that sensor so i didn’t catch tha issue.

The change you made should resolve the problem.
