### ISSUE TITLE
How to for newbie... sorry

### ISSUE THREAD

**Issue by 40federico** [jello1974/duosidaEV-home-assistant#5]
Hi
I am not experienced in programing. And not clear idea on how integrate your code in home assistant. I have already HACS running but how to connect your integration....
I read "copy the folder",... what folder? where is the folder? sorry, I know too basic questions....

In other order of questions, how is Duosida charger? I have other brand installed, no possible to connect with home assistant and with some troubles. I have decided to replace and not sure if Duosida is a good option. As the rest of the people I have solar panels and would like to automate the process to use only free energy for charging purposes.

Thanks a lot.

**Comment by 40federico** [comment]
> Hi I am not experienced in programing. And not clear idea on how integrate your code in home assistant. I have already HACS running but how to connect your integration.... I read "copy the folder",... what folder? where is the folder? sorry, I know too basic questions....
> 
> In other order of questions, how is Duosida charger? I have other brand installed, no possible to connect with home assistant and with some troubles. I have decided to replace and not sure if Duosida is a good option. As the rest of the people I have solar panels and would like to automate the process to use only free energy for charging purposes.
> 
> Thanks a lot.

Solved... finally easy (when you know how to do...). I have installed HA over VM in Synology and the access to files is tricky. Solved deploying Samba. Thanks.

**Comment by jello1974** [comment]
I'm glad you solve it
