### ISSUE TITLE
Integration asks me for username and password

### ISSUE THREAD

**Issue by spac3h** [jello1974/duosidaEV-home-assistant#6]
Integration asks me for username and password but i don't have one.

<img width="377" alt="image" src="https://github.com/jello1974/duosidaEV-home-assistant/assets/20891430/cc5cd831-fa05-4919-ac51-338bd6ba0179">

Any ideas on how to overcome this issue?

**Comment by jello1974** [comment]
you have to install duosida app and register your device....

**Comment by spac3h** [comment]
Thanks, it's working. I was using the orange app instead of the blue one.

**Comment by jello1974** [comment]
I'm glad you managed to use it. I never tested it with the orange app....
